[tool.poetry]
name = "peakventures"
version = "1.2.2"
description = "PeakVentures Python Utilities for DataBricks"
authors = ["Volodymyr Smirnov <volodymyr@peakventures.co>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.28.11"
tenacity = "^8.2.2"
websockets = "^11.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
