[tool.poetry]
name = "lsjsonclasses"
version = "1.1.3"
description = "Custom json encoder/decoder for python types"
authors = ["IT <it@electronic-shop.lu>"]

[tool.poetry.dependencies]
python = "^3.8"
iso8601 = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
