[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name="pylette-windows"
version="2.0.0"
description="Pylette for Windows"
readme="README.md"
authors=[{ name = "Austin Bryant", email = "c00481025@louisiana.edu" }]
license={ file = "LICENSE.md" }
classifiers=[
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords=["palette", "color", "image"]
dependencies=[
    "numpy==1.24.3",
    "Pillow>=10.0.0",
    "PyQt5>=5.15.9",
    "scikit-learn>=1.3.0"
]
requires-python=">=3.11.4"

[project.urls]
Homepage="https://github.com/IntoThatGoodNight/Pylette-Windows-Fork"

[project.scripts]
pylette="pylette.palette:main"