---
name: ğŸ¦„ Code Linting & Scanning


on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main


# Limit workflow to one job per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


env:
  STABLE_PYTHON_VERSION: '3.9'
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"


jobs:
  code-quality:
    name: ğŸ’„ Code Quality
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“© Checkout the source w/ full depth(for tags and SCM)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: ğŸ Setup Python ${{ env.STABLE_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.STABLE_PYTHON_VERSION }}


      - name: ğŸŒ± Linting with black
        run: |
          mkdir -p /tmp/artifacts
          make install
          make lint


      - name: ğŸ¦¹â€â™‚ï¸ Scanning with bandit
        run: |
          make bandit > /tmp/artifacts/bandit_scan.txt || $( exit 0 ); echo $?


      - name: ğŸ–‹ï¸ mypy Type Checking
        run: |
          make type > /tmp/artifacts/mypy.txt || $( exit 0 ); echo $?


      - name: ğŸ“ Archiving Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ !failure() }}
        continue-on-error: true
        with:
          name: scan-artifacts
          retention-days: 1
          path: |
            /tmp/artifacts