[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scratch-getdata"
version = "1.0.8"
authors = [
  { name="kokofixcomputers", email="kokocanfixit@kokofixcomputers.serv00.net" },
]
dependencies = ['requests']
description = "A Module to fetch scratch things from ScratchGetData"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Github" = "https://github.com/scratch-getdata/scratch-getdata-python"
"Bug Tracker" = "https://github.com/scratch-getdata/scratch-getdata-python/issues"