[tool.poetry]
name = "edu_rdm_integration"
version = "0.1.2"
description = "Интеграция с Региональной витриной данных"
authors = ["BARS Group"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.semantic_release]
version_variable = "pyproject.toml:version"

[tool.isort]
multi_line_output = 3
force_grid_wrap = "True"
include_trailing_comma = "True"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
line_length = 1
combine_as_imports = "True"
lines_after_imports = 2
skip_glob = "**/migrations/*.py"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
