[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pythomac_sebastian.schwindt"
version = "1.0.0"
authors = [
  { name="Hydro-Informatics.com", email="schwindt.water@gmail.com" },
]
description = "A Python package with codes to wrap and control the numerical modeling software Telemac."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hydro-informatics/pythomac"
"Bug Tracker" = "https://github.com/hydro-informatics/pythomac/issues"
