[tool.poetry]
name = "intellect_core"
version = "0.2.1"
description = "Модуль интеграции с Интеллект"
authors = ["Mrkorogod"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

