[tool.poetry]
name = "examon_beginners_package"
version = "0.0.10"
description = ""
authors = ["Jarrod Folino <jdfolino@icloud.com>"]
packages = [{include = "examon_package_template"}]


[tool.poetry.dependencies]
python = "^3.9"
examon-core = "1.0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
